chore: update CODEOWNERS, remove johannes-gehrs
moia-oss/aws-codepipeline-trigger pull request #148
Opened 2023-01-13 09:36 UTC by cbrgm

2023-01-13 09:37 UTC, djablonski-moia approved these changes

2023-01-13 15:50 UTC, oppermax requested changes

2023-01-13 15:50 UTC, oppermax commented on CODEOWNERS
> +*   @msiuts @bemica @snowiow @guusvw @djablonski-moia @oppermax @cbrgm
``` suggestion
*   @msiuts @bemica @snowiow @guusvw @djablonski-moia @oppermax @cbrgm @karo-moia 
```

2023-01-16 12:29 UTC, djablonski-moia submitted a review, later dismissed

2023-01-16 12:34 UTC, djablonski-moia commented
The failing checks can't be related to the change is this PR :thinking:

2023-01-16 12:36 UTC, cbrgm commented
Yeah I'll do a rebase

2023-01-16 12:55 UTC, djablonski-moia commented
@oppermax needs to review anyway, since he requested changes :wink:

2023-01-16 12:56 UTC, oppermax approved these changes

2023-01-16 12:57 UTC, merged